### ISSUE TITLE
Resleeving aka "Флешки"

### ISSUE THREAD

**Issue by dangranos** [animusdev/blue#478]
На форум лезть лень, так что спрошу здесь. Есть ли в планах фича с флешками с BayStation12? (которые там для игроков "neural lace" хотя по коду они "cortical stack")

**Comment by LethalGhost** [comment]
Были идеи на старом блу. Тут пока не думали о таком.

**Comment by LethalGhost** [comment]
Что-то я перепутал все.
Нет, таких планов не было.
