### ISSUE TITLE
Вахтерша и дормы

### ISSUE THREAD

**Issue by dangranos** [animusdev/blue#483]
В связи с размером дормов, а по сути 12 отдельных квартир со всеми удобствами (разве что бара нету), стоит ввести еще одну профессию для аутирования, а именно надзирателя дорм или как-нибудь еще обозвать.
А что бы не сидел без дела, сделать некий "Dorm controller" у каждой двери, который будет показывать состояние комнаты. Например: зеленый - не занято, желтый - комната заселена, но открыта, и красный - вход только для владельца комнаты (и если добавить возможжность больше одного человека в доступ комнаты писать, по сути вайтлист, то и им тоже).
И всеми этими контроллерами управлять с одного пульта вахтерши у входа.

Тапками себя могу закидать сам.

**Comment by Euronem** [comment]
> Тапками себя могу закидать сам.
можешь начинать.

**Comment by dangranos** [comment]
Это было больше идея для обсуждения. Кода пока никакого нету, что бы закидывать.

**Comment by LethalGhost** [comment]
Вахтер - фан, но такой себе.
А вот с домофонами, типами замков с Бея и прочим можно повеселиться.
