### ISSUE TITLE
Астероид и генерация руд.

### ISSUE THREAD

**Issue by dangranos** [animusdev/blue#495]
Возможно в конфигах уже стоит, но я тут заметил, что для спавна минералов требуется указать в конфиге з-уровни, на которых они могут спавниться.
`ASTEROID_Z_LEVELS 1;4;5` - стоит по дефолту в конфиге, который дан как пример.
Код: https://github.com/animusdev/blue/blob/f8ef2e0c37c2da786d5e2691cb297264f604a7bf/code/world.dm#L86

**Comment by LethalGhost** [comment]
В целом, странно, что не карта определяет кем она является, а конфиг.
Спасибо за сообщение.
