### ISSUE TITLE
Раунды не начинаются, если игроков на сервере меньше 5

### ISSUE THREAD

**Issue by Divix01** [animusdev/blue#512]
Суть в заголовке. На локалке всё пашет, ставится экста, а на блю секрет и ошибка:
Unable to choose playable game mode. Reverting to pre-game lobby.

**Comment by LethalGhost** [comment]
Экста не включена в список возможных режимов. В этом соль.

**Comment by Divix01** [comment]
Так и что, эксту добавят в список возможных режимов или? Ночные раунды не начинаются.
