### ISSUE TITLE
Зарядники для мехов проёбаны

### ISSUE THREAD

**Issue by Spaint** [animusdev/blue#516]
![2fd8e620](https://cloud.githubusercontent.com/assets/1905699/17278036/eee6893e-5773-11e6-9f7d-2aafdda6d400.png)

**Comment by Euronem** [comment]
Бля, а я думал, что это фича такая.

**Comment by dangranos** [comment]
Странно, вроде это и есть фича, нет?

**Comment by Spaint** [comment]
@dangranos Некрасивые тёмные тайлы и отсутствие компьютера как бы намекают. Даже если это фича, то фича убогая.

**Comment by LethalGhost** [comment]
На сколько я понимаю, это именно убогая фича.
