### ISSUE TITLE
Ебучие нерфобляди

### ISSUE THREAD

**Issue by Aidff** [animusdev/blue#551]
Хули я в свои любимые сигары и сигареты не могу трика залить и спокойно его покуривать? Или врагу форона залить? Возвращай все как было и триторам сигаретки верни!

**Comment by RandomColonist** [comment]
Их макнуть можно в ёмкость с нужной жидкостью, ало.

**Comment by Aidff** [comment]
Может тебя головой в унитаз макнуть? Всегда все через шприц было, макнуть, вообще охуеть.

**Comment by RandomColonist** [comment]
Ути-пути, какие мы агрессивные. Мне больше представляется реальным и удобным макать сигареты в ёмкость, нежели вводить что-то через шприц. Вытекать же будет, ну.

**Comment by Aidff** [comment]
А еще с ними теперь есть баг и сигары меньше жидкости вмещают (точнее столько же сколько сигареты) Баг не критичный, но забавный. Нет побочных эффектов от лекарств выкуренных через сигарету.

**Comment by LethalGhost** [comment]
SMTH #645
