### ISSUE TITLE
Combat Armor & Тонкотрапы

### ISSUE THREAD

**Issue by RandomColonist** [animusdev/blue#553]
У гаунтлетов (перчаточек) и бутсов (ботиночек) нет спрайтов на тонкотрапов. Подозреваю, что и остальной фуллсетной брони такого типа их тоже нет (риот, тактикал, булетпруф, аблатив).

**Comment by Aidff** [comment]
Щас бы тонкотрапом в фулсетах побегать.

**Comment by LethalGhost** [comment]
Спрайтопроблем очень и очень много. Пока репорты о тонких спрайтах не принимаются.
