### ISSUE TITLE
Tritar

### ISSUE THREAD

**Issue by Aidff** [animusdev/blue#557]
Вкалываешь аплинк имплант, получаешь имплант на ноль очков) Здорово)

**Comment by RandomColonist** [comment]
Чисто предположение - может его нужно сперва заправить кристаллами, изъятыми из изначального апплинка?

**Comment by Aidff** [comment]
Простите, какого хуя? Этого нет в описании, это интуитивно нихуя не понятно и как ты вообще себе представляешь запихивание в имплантер кристалов? Это же обычный шприц только с имплантом. Мне кажется, это конкретно баг, а не фича.
