### ISSUE TITLE
Холодильник в баре

### ISSUE THREAD

**Issue by Sayders** [animusdev/blue#561]
Он багается и вылезает пуская менюшка, если:
1) сувать туда стаканы с трубочками/палочками
2) термосы, фляги
3) что-то еще, но не знаю точно, что

**Comment by Divix01** [comment]
Перепроверь, возможно сервер не обновился на тот момент.

**Comment by Sayders** [comment]
Нихуя. Еще если бутылку Space-up запихнуть - тоже ломается.

**Comment by Divix01** [comment]
Заскринь что ли, у меня не получается повторить баг, а у меня самые блджадышь наножуи.
