### ISSUE TITLE
Телега уборщика

### ISSUE THREAD

**Issue by Sayders** [animusdev/blue#562]
Если налить в нее воды, то нет возможности щетку в нее убрать. Только намочить можно.

**Comment by Spaint** [comment]
Раньше она засовывалась только если швабра намочена по-максимуму, а иначе - мочилась. На Полярисе не проверял.

**Comment by Ahmedok** [comment]
Плюсую, мешает играть за уборщика.

**Comment by dangranos** [comment]
Поведение такое же, как и до этого. Швабра сначала мочится, и только потом, если она полностью мокрая, ложится

**Comment by Sayders** [comment]
Закодьте так, чтобы через альт она убиралась вне зависимости от того, насколько мокрая. Будет заебись.

**Comment by Divix01** [comment]
@dangranos ложь. Если швабра мокрая, то на данной сборке она не ложится, в отличие от бея. Необходимо полностью опустошить ведро у тележки.

**Comment by alfacom** [comment]
@Divix01 только вчера за уборщика на сервере проверял. Налил воды до краев, пару раз помочил, затем положил в телегу. Достал, вытер пол, ~~упал, т.к. забыл сапоги,~~ опять помочил и положил обратно.

**Comment by Divix01** [comment]
@alfacom я не знаю что и где ты проверял, но пруф или пиздабол: http://prntscr.com/c4xe05
Мб намочил "пару раз" до опустошения ведра в телеге?

**Comment by alfacom** [comment]
А ты попробуй залить жидкости по полной.

12 авг. 2016 г. 20:35 пользователь "Divix01" <notifications@github.com>
написал:

**Comment by Divix01** [comment]
@alfacom увидел.
Всё сделано как просили: через alt кладется также, как и если иметь полностью намоченную швабру (30 юнитов = 3 клика по 10 юнитов; раньше 6 кликов по 5 юнитов).
