### ISSUE TITLE
Силикон (укрепляет окна) из клинера убирается весь за раз при нажатии на окно

### ISSUE THREAD

**Issue by Sayders** [animusdev/blue#578]

**Comment by Divix01** [comment]
Про фичу с укреплением окон первый раз слышу (спасибо за это кста), но из клинера не убирается весь силикон за раз при нажатии на окно. Проверено.
http://prntscr.com/c4x9jo

**Comment by Sayders** [comment]
Что-то гон. Я проверял последний раз - сразу весь исчезает. Закачал туда единиц 80 - он сразу весь на окно тратит.

**Comment by Divix01** [comment]
@Sayders пруф или закрывай)
