### ISSUE TITLE
Извечная проблема дронов и труб

### ISSUE THREAD

**Issue by alfacom** [animusdev/blue#584]
Дронам просто как воздух нужен RPC (Rapid Pipe Constructor) ибо:

0) Его нету у дронов, возможно нет и у боргов.
1) Таскать по одной атмосотрубе ооооочень геморойно.
2) Дроны не могут таскать мусорные трубы ибо они СЛИШКОМ ТЯЖЕЛЫ для них.

В итоге становится просто невозможно пофиксить последствия взрывов, если взрыв задел трубы.

К слову мусорные трубы должны входить в список поглощаемых вещей у маттер декомпилера, дабы их можно было убрать, если промахнулся с местом их спавна.

Я пилил порт RPC с VG на ранний блю и, кажется, кто-то пилил свою версию RPC на поздний блю.
Кто запилит его сейчас? Кто станет героем в этой новой эпохе блю? Чье имя будут скандировать невидимые помощники инженеров?

**Comment by Aidff** [comment]
90% процентов дронов ебучие мстители

**Comment by alfacom** [comment]
80% игроков ебучие мстители. Просто не все признаются. Но разговор не об этом.
Чем же рпц поспособствует их мщению?

**Comment by alfacom** [comment]
Закрываемся, ибо мержнуто.
