### ISSUE TITLE
Пожарный топор.

### ISSUE THREAD

**Issue by Ahmedok** [animusdev/blue#595]
Он двуручен всегда, пока во второй руке ничего нет. При этом, "вторая рука" не отображается во второй руке, а вручную перевести топор в одноручное состояние нельзя.

**Comment by Spaint** [comment]
Это фича

**Comment by RandomColonist** [comment]
Из-за этой фичи его нельзя вернуть обратно в кейс. Фиксите кейс.

**Comment by Ahmedok** [comment]
Я все проверил, фича вроде норм, но лишает ручного контроля. Чтобы вернуть его, нужно взять в другую руку что-то, и выбрав топор, вернуть его.
