### ISSUE TITLE
Мерджи с полярисом

### ISSUE THREAD

**Issue by RandomColonist** [animusdev/blue#602]
У меня такое впечатление, что мы ВООБЩЕ не мерджимся с полярисом в плане фич, фиксов и прочей хуйни, не говоря уже про маппу. Где всё это?

http://hkar.ru/Kk48

**Comment by Divix01** [comment]
НАХУЙ ТВОИ МЕРДЖИ.
Фичи, введенные здесь удаляются, лишняя херь прибавляется. Если что-то конкретно интересует - то это и руками можно взять.

**Comment by RandomColonist** [comment]
Фиксы багов у них тоже брать не будете? Вашего говнокода в билде уже хватает. Давай я тебе буду отдельно пулы скидывать, которые нам бы пригодились?

**Comment by Divix01** [comment]
Говнокода особого (да и просто кода) от энтузиастов тут нету как не странно. По поводу пулов: тебе ничего не мешает копипастить коммиты/пулы с полярки (да и не только с полярки так-то) сюда. Это не сложно, только надо совсем немного с гитом поработать и потратить свое время.
