### ISSUE TITLE
Завезите нормальных взаимодействий со счетами для хопа

### ISSUE THREAD

**Issue by Sayders** [animusdev/blue#605]
Ну, там возможность совершать перевод с главного счета на остальные и так далее. Типа возможность начислять зарплату/премии и так далее.

**Comment by RandomColonist** [comment]
На бее есть рудиментарное начисление и снятие со счёта, а вот на полярисе и такого нет.

**Comment by Divix01** [comment]
Как по мне, так сомнительная фича. Дело в том, что это не нормально. Вот приходишь ты на работу, говоришь "Вот у меня карта сбербанка, начисляйте сюда зп", а насяльника берет и удаляет счет, переводя деньги на счет фирмы. 
Откуда у него вообще доступ к счету? 
Да, это сс-ка, колония мать его, поэтому может быть аналог банка, но мне кажется, что без правил и с аутистичными педалями из-за "я хоп епта, делаю чо хочу" или "проявляю инициативу, у всех неработающих закрываю счет и перевожу деньги. Мне срать что эти деньги - ваши пенсионные накопления" ничего путного не получится.

**Comment by alfacom** [comment]
> Откуда у него вообще доступ к счету?
Просто ХоП работает в сбербанке. Да и вся колония принадлежит сбербанку.

16 августа 2016 г., 20:20 пользователь Divix01 <notifications@github.com>
написал:

**Comment by Sayders** [comment]
Суть в том, что ты и так можешь сейчас заблокировать счет/перевести деньги на счет фирмы. Так что надо возможность обратных действий: начисление премий и так далее.

**Comment by alfacom** [comment]
А теперь веселое. 
Сейчас это выглядит так:
Раздел "CentCom Administrator"
Revoke и его кнопочка
Если есть доступ центкома показать еще две кнопки: Add Funds и Remove Funds.

Я могу это поправить, но вопрос как именно.
На мой взгляд надо вытащить Add & Remove Funds из проверки доступа, да и вообще из раздела "CentCom Administrator", а Revoke и сам раздел запихнуть в проверку доступа.
То есть:
Две кнопки: Add Funds и Remove Funds.
Если есть доступ центкома показать раздел "CentCom Administrator" и кнопку Revoke

**Comment by Sayders** [comment]
Отзыв зарплаты должен и так быть, вне зависимости цк ты или нет. Просто добавь возможность трансферить их.

**Comment by alfacom** [comment]
Revoke забирает все деньги со счета жертвы исключительно на счет станции.
Трансфер я добавил, и он позволяет сделать то же, что и revoke, но с любой
суммой в пределах доступной на счете и на любой счет.
