### ISSUE TITLE
Автолатопроблемы

### ISSUE THREAD

**Issue by RandomColonist** [animusdev/blue#630]
Либо эту хуйню нужно выпилить из рецепта, либо я не ебу, что она тут делает. Я про waste.
http://prntscr.com/c804qi

**Comment by alfacom** [comment]
Веселая хрень. На оригинальном полярисе она тоже есть, но вот кода к ней я не нашел... А ведь без нее ни один девайс не хочет печататься. Надо на бей глянуть

**Comment by Camper12345** [comment]
#645 Сделал
