### ISSUE TITLE
Labeler

### ISSUE THREAD

**Issue by RandomColonist** [animusdev/blue#631]
Сделать наклейки каким-то образом снимаемыми. В основном для брига, чтоб можно было без опасения обклеить шмотки, а потом, когда офицер уснёт, эти наклейки убрать. Предлагаю делать это с выключенным лейблером.

**Comment by Camper12345** [comment]
Как-то жирновато. Это вряд ли бумажка, скорее всего краской надпись. Тогда можно смывать чем-то моющим, мылом, например.

**Comment by RandomColonist** [comment]
Любой вариант устроит, лишь бы возможность была.

**Comment by Camper12345** [comment]
#645 Сделал
