### ISSUE TITLE
Мадман пися

### ISSUE THREAD

**Issue by RandomColonist** [animusdev/blue#651]
Добавьте сюда лампочку, наконец. Нихера не видно без фонарика, когда стоишь внутри. И раз решили ставить такой тип стекла - впилите его крафт, что-ли. Ну или замените его на затеняющееся по кнопке, да и дверцу неплохо было бы сделать непрозрачной.
http://prntscr.com/chx1n4

**Comment by alfacom** [comment]
Просто реагенты в лаборатории реагируют на свет, поэтому там и должно быть
темно.

14 сент. 2016 г. 16:40 пользователь "RandomColonist" <
notifications@github.com> написал:
